### ISSUE TITLE
IconImageManager does not understand #value:

### ISSUE THREAD

**Issue by tukanos** [jgfoster/Jade#89]
Hello,

I'm using `[Jade v2.4.34](https://github.com/jgfoster/Jade/releases/tag/2.4.34)` and sometimes I get message:

`IconImageManager does not understand #value:` .  If I click on OK button then it disappears.

**Comment by jgfoster** [comment]
Fixed in release 2.4.37.

**Comment by tukanos** [comment]
> Fixed in release 2.4.37.

Great work James.  This bug is extremely annoying when you are debugging.   

If I may ask, what was the issue?  I'm looking at the patch but it is rather cryptic.

**Comment by tukanos** [comment]
@jgfoster The bug is still present.  I have tried latest version of Jade and it still shows.

Here is the situation's screenshot, with the error:

<img width="5120" height="2160" alt="Image" src="https://github.com/user-attachments/assets/181b7775-98d7-416b-a108-528169a62975" />

Here is the updated Jade version:

<img width="5120" height="2160" alt="Image" src="https://github.com/user-attachments/assets/27e314a9-3601-4841-a55a-8c74679d21a8" />

**Comment by jgfoster** [comment]
@tukanos, Thanks for the follow-up. I noticed the problem whenever the mouse moved over the footer/status bar at the bottom of the System Browser. The problem was that it was configured to give a tool-tip but the tool-tip wasn't implemented. I turned off the tool-tip flag and the problem went away in that instance. Evidently there are other widgets that have the same problem. By moving the mouse slowly over all parts of the window, can you discern which widget has the problem? I'll do the same as well...

**Comment by jgfoster** [comment]
@tukanos, I've found a couple other places (I saw that you had the method list browser open) and created v2.4.38. I'll leave the issue open for you to try the new version and close the issue if you find it fixed.

**Comment by tukanos** [comment]
@jgfoster I see.  I was wondering what window feature is it trying to call.  I just cruised through it when looking.

Thank you for further update.  I'll be checking it for sure.

**Comment by tukanos** [comment]
@jgfoster The issue seems to be resolved.  I have not encountered it anymore and I tried :).

**Comment by jgfoster** [comment]
Thanks, I'll close the issue. Feel free to reopen if you can reproduce it.
